=== AstralJaeger-University/SSD4-UE04/xmlfiles/ue4_fitnessdokument.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified"xmlns:fit="http://www.fitness.at" targetNamespace="http://www.fitness.at">	<xs:element name="Fitnessdokument" type="fit:DokType">		<xs:key name="mgId">			<xs:selector xpath="fit:Messgeräte/fit:Messgerät"></xs:selector>			<xs:field xpath="@id"></xs:field>		</xs:key>			<xs:keyref name="refmgId" refer="fit:mgId">			<xs:selector xpath="fit:Vitaldaten/fit:Messung"></xs:selector>			<xs:field xpath="@messgerätId"></xs:field>		</xs:keyref>		</xs:element>		<xs:complexType name="DokType">		<xs:sequence>			<xs:element ref="fit:Person"/>			<xs:element name="Vitaldaten" type="fit:VitaldatenType">			</xs:element>			<xs:element name="Grenzwertliste" type="fit:GrenzwertlisteType"/>			<xs:element name="Messgeräte" type="fit:MessgeraeteType"/>			<xs:element ref="fit:Medikationsliste" minOccurs="0"/>		</xs:sequence>		<xs:attribute name="erzeugt" type="xs:string"/>		<xs:attribute name="version" type="xs:integer"/>	</xs:complexType>									<xs:complexType name="MessgeraeteType">		<xs:sequence>			<xs:element name="Messgerät" type="fit:MessgeraetType" maxOccurs="unbounded"/>		</xs:sequence> 	</xs:complexType>	<xs:complexType name="GrenzwertlisteType">		<xs:sequence>			<xs:element name="Grenzwert" type="fit:GrenzwertType" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="VitaldatenType">		<xs:sequence>			<xs:element name="Messung" type="fit:MessungType" maxOccurs="unbounded">							</xs:element>		</xs:sequence>	</xs:complexType>										<xs:complexType name="MesswertType">		<xs:attribute name="typ" type="fit:messwertTypType">		</xs:attribute>		<xs:attribute name="wert" type="xs:double"/>		<xs:attribute name="einheit" type="xs:string"/>	</xs:complexType>		<xs:complexType name="MessungType">		<xs:sequence>			<xs:element name="Messwert" type="fit:MesswertType" maxOccurs="unbounded">			</xs:element>			<xs:element name="Notiz" type="xs:string" minOccurs="0"/>			<xs:element name="Messbedingung" type="xs:string" minOccurs="0"/>		</xs:sequence>		<xs:attribute name="typ" type="fit:messungType" use="required">		</xs:attribute>		<xs:attribute name="zeitpunkt" type="xs:dateTime" use="required"/>		<xs:attribute name="messgerätId" type="fit:mgIdType">		</xs:attribute>	</xs:complexType>		<xs:simpleType name="messwertTypType">		<xs:restriction base="xs:string">			<xs:enumeration value="Diastolisch"/> 			<xs:enumeration value="Systolisch"/> 			<xs:enumeration value="Blutzucker"/> 			<xs:enumeration value="Gewicht"/> 			<xs:enumeration value="Puls"/> 			<xs:enumeration value="Schritte"/>		</xs:restriction>								</xs:simpleType>	<xs:simpleType name="messungType">		<xs:restriction base="xs:string">			<xs:enumeration value="BlutdruckPuls"/>			<xs:enumeration value="Blutzucker"/>			<xs:enumeration value="Gewicht"/>			<xs:enumeration value="Schritte"/>								</xs:restriction>	</xs:simpleType>	<xs:complexType name="GrenzwertType">		<xs:sequence>			<xs:element name="Schwellwert" maxOccurs="unbounded" type="fit:SchwellwertType"/>		</xs:sequence>		<xs:attribute name="typ" type="fit:messwertTypType" use="required"/>		<xs:attribute name="von" type="xs:date" use="optional"/>		<xs:attribute name="bis" type="xs:date" use="optional"/>			</xs:complexType>			<xs:complexType name="SchwellwertType">		<xs:attribute name="typ" type="fit:schwellwertTypType"></xs:attribute>		<xs:attribute name="wert" type="xs:double"/>		<xs:attribute name="einheit" type="xs:string"/>	</xs:complexType>	<xs:simpleType name="schwellwertTypType">		<xs:restriction base="xs:string">			<xs:enumeration value="unten"/>			<xs:enumeration value="oben"/>		</xs:restriction>	</xs:simpleType>			<xs:element name="Person" type="fit:SVPersonType"/>	<xs:complexType name="PersonType">		<xs:sequence>			<xs:element name="Titel" type="fit:TitelType" minOccurs="0" maxOccurs="unbounded"/>			<xs:element name="Vorname" type="fit:NameType" minOccurs="0" maxOccurs="6"/>			<xs:element name="Nachname" type="fit:NameType" maxOccurs="2"/>		</xs:sequence>		<xs:attribute name="geschlecht" type="fit:GeschlechtType" use="required"/>		<xs:attribute name="geburtsdatum" type="xs:date"/>	</xs:complexType>	<xs:simpleType name="NameType">		<xs:restriction base="xs:string">			<xs:minLength value="1"/>			<xs:maxLength value="50"/>		</xs:restriction>	</xs:simpleType>	<xs:complexType name="TitelType">		<xs:simpleContent>			<xs:extension base="xs:string">				<xs:attribute name="position">					<xs:simpleType>						<xs:restriction base="xs:string">							<xs:enumeration value="vor"/>							<xs:enumeration value="nach"/>						</xs:restriction>					</xs:simpleType>				</xs:attribute>			</xs:extension>		</xs:simpleContent>	</xs:complexType>	<xs:simpleType name="GeschlechtType">		<xs:restriction base="xs:string">			<xs:enumeration value="männlich"/>			<xs:enumeration value="weiblich"/>			<xs:enumeration value="inter"/>			<xs:enumeration value="divers"/>			<xs:enumeration value="unbekannt"/>		</xs:restriction>	</xs:simpleType>	<xs:complexType name="SVPersonType">		<xs:complexContent>			<xs:extension base="fit:PersonType">				<xs:attribute name="svnr">					<xs:simpleType>						<xs:restriction base="xs:long">							<xs:totalDigits value="10"/>						</xs:restriction>					</xs:simpleType>				</xs:attribute>			</xs:extension>		</xs:complexContent>	</xs:complexType>		<xs:element name="Medikationsliste" type="fit:MedikationslisteType"/>	<xs:complexType name="MedikationslisteType">		<xs:sequence>			<xs:element name="Medikation" type="fit:MedikationType" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="MedikationType">		<xs:simpleContent>			<xs:extension base="xs:string">				<xs:attribute name="einnahme" use="required">					<xs:simpleType>						<xs:restriction base="xs:string">							<xs:enumeration value="täglich"/>							<xs:enumeration value="bei Bedarf"/>						</xs:restriction>					</xs:simpleType>				</xs:attribute>				<xs:attribute name="dosierung" type="xs:string"/>				<xs:attribute name="diagnose" type="xs:string"/>				<xs:attributeGroup ref="fit:zeitraumVonBis"/>				<xs:attribute name="anwendung" type="xs:string" use="required"/>				<xs:attribute name="hinweis" type="xs:string"/>			</xs:extension>		</xs:simpleContent>	</xs:complexType>	<xs:attributeGroup name="zeitraumVonBis">		<xs:attribute name="von" type="xs:date" use="optional"/>		<xs:attribute name="bis" type="xs:date" use="optional"/>	</xs:attributeGroup>		<xs:element name="Messgerät" type="fit:MessgeraetType">		</xs:element>	<xs:complexType name="MessgeraetType">		<xs:sequence>			<xs:element name="Gerätetyp" type="xs:string"></xs:element>			<xs:element name="Hersteller" type="xs:string"></xs:element>			<xs:element name="Modellnummer" type="xs:string"></xs:element>			<xs:element name="Seriennummer" type="xs:string"></xs:element>		</xs:sequence>		<xs:attribute name="id" type="fit:mgIdType"/>	</xs:complexType>		<xs:simpleType name="mgIdType">			<xs:restriction base="xs:string">				<xs:pattern value="mg_[a-z]{2}[0-9]"/>			</xs:restriction>		</xs:simpleType></xs:schema>

=== AstralJaeger-University/SSD4-UE04/xmlfiles/ue4_fitnessdokument.xml
<?xml version="1.0" encoding="UTF-8"?>
<Fitnessdokument erzeugt="2024-03-01T08:46:00+01:00" version="3" xmlns="http://www.fitness.at"  xmlns:fit="http://www.fitness.at" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.fitness.at ue4_fitnessdokument.xsd">
	<Person geschlecht="weiblich" geburtsdatum="1971-08-24" svnr="8567240856">
		<Titel position="nach">MSc</Titel>
		<Titel position="vor">Mag.</Titel>
		<Vorname>Sandra</Vorname>
		<Nachname>Sportlich</Nachname>
	</Person>
	<Vitaldaten>
		<Messung typ="BlutdruckPuls" zeitpunkt="2024-01-28T07:55:42" messgerätId="mg_bd1">
			<Messwert typ="Systolisch" wert="121.0" einheit="mmHg"/>
			<Messwert typ="Diastolisch" wert="70.0" einheit="mmHg"/>
			<Messwert typ="Puls" wert="79.0" einheit="Schläge/min"/>
			<Notiz>Maschinell</Notiz>
		</Messung>
		<Messung typ="Gewicht" zeitpunkt="2024-01-28T08:45:29" messgerätId="mg_wg1">
			<Messwert typ="Gewicht" wert="80.6" einheit="kg"/>
		</Messung>
		<Messung typ="Schritte" zeitpunkt="2024-01-28T00:00:00" messgerätId="mg_ft1">
			<Messwert typ="Schritte" wert="9800"/>
			<Notiz>Maschinell</Notiz>
		</Messung>
		<Messung typ="BlutdruckPuls" zeitpunkt="2024-01-27T07:48:28" messgerätId="mg_bd1">
			<Messwert typ="Systolisch" wert="115.0" einheit="mmHg"/>
			<Messwert typ="Diastolisch" wert="67.0" einheit="mmHg"/>
			<Notiz>Maschinell</Notiz>
		</Messung>
		<Messung typ="Gewicht" zeitpunkt="2024-01-22T09:05:51" messgerätId="mg_wg1">
			<Messwert typ="Gewicht" wert="80.7" einheit="kg"/>
			<Notiz>Maschinell</Notiz>
		</Messung>
		<Messung typ="Schritte" zeitpunkt="2024-01-20T00:00:00" messgerätId="mg_ft2">
			<Messwert typ="Schritte" wert="6320" einheit="pro Tag"/>
		</Messung>
		<Messung typ="Blutzucker" zeitpunkt="2024-01-28T08:44:47" messgerätId="mg_bz1">
			<Messwert typ="Blutzucker" wert="155.5" einheit="mg/dl"/>
			<Messbedingung>nach dem Essen</Messbedingung>
		</Messung>
		<Messung typ="Blutzucker" zeitpunkt="2024-01-27T07:49:13" messgerätId="mg_bz1">
			<Messwert typ="Blutzucker" wert="201.5" einheit="mg/dl"/>
			<Messbedingung>nach dem Essen</Messbedingung>
		</Messung>
	</Vitaldaten>
	<Grenzwertliste>
		<Grenzwert typ="Schritte" von="2024-01-01" bis="2024-01-22">
			<Schwellwert typ="unten" wert="10000" einheit="pro Tag"/>
		</Grenzwert>
		<Grenzwert typ="Blutzucker" von="2024-01-01" bis="2024-01-28">
			<Schwellwert typ="unten" wert="80" einheit="mg/dl"/>
			<Schwellwert typ="oben" wert="160" einheit="mg/dl"/>
		</Grenzwert>
	</Grenzwertliste>
	<Messgeräte>
		<Messgerät id="mg_bd1">
			<Gerätetyp>Blutdruck-Messgerät</Gerätetyp>
			<Hersteller>A/D Medical</Hersteller>
			<Modellnummer>UA-767NFC</Modellnummer>
			<Seriennummer>51204 00454</Seriennummer>
		</Messgerät>
		<Messgerät id="mg_wg1">
			<Gerätetyp>Waage</Gerätetyp>
			<Hersteller>Wahoo Fitness</Hersteller>
			<Modellnummer>WFBTScalev1</Modellnummer>
			<Seriennummer>40355 42306255</Seriennummer>
		</Messgerät>
		<Messgerät id="mg_ft1">
			<Gerätetyp>Fitness Tracker</Gerätetyp>
			<Hersteller>Polar</Hersteller>
			<Modellnummer>loop-90047656</Modellnummer>
			<Seriennummer>73539 012302</Seriennummer>
		</Messgerät>
		<Messgerät id="mg_ft2">
			<Gerätetyp>Fitness Tracker</Gerätetyp>
			<Hersteller>Garmin</Hersteller>
			<Modellnummer>vivofit</Modellnummer>
			<Seriennummer>3F7019550</Seriennummer>
		</Messgerät>
		<Messgerät id="mg_bz1">
			<Gerätetyp>Blutzuckermesser</Gerätetyp>
			<Hersteller>Aktivmed</Hersteller>
			<Modellnummer>GlucoCheckXL</Modellnummer>
			<Seriennummer>12231 23128829</Seriennummer>
		</Messgerät>
	</Messgeräte>
	<Medikationsliste xmlns="http://www.fitness.at">
		<Medikation einnahme="täglich" dosierung="1-0-1-0" von="2022-12-21" bis="2024-01-24" anwendung="zum Einnehmen">
			Diazepam Actavis 10 mg Tabletten</Medikation>
		<Medikation einnahme="täglich" dosierung="1-0-0-0" hinweis="vor dem Frühstück" anwendung="zum Einnehmen">Zithromax 250 mg Filmtabl.</Medikation>
		<Medikation einnahme="täglich" hinweis="3x2 Tropfen" anwendung="nasal">Nasivin 0,05 % - Nasentropfen</Medikation>
		<Medikation einnahme="bei Bedarf" dosierung="1-1-1-0" anwendung="zum Einnehmen">Seractil</Medikation>
	</Medikationsliste>
</Fitnessdokument>
